#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# Wechall indentification
export WECHALLUSER="hatnguyen"
export WECHALLTOKEN="ACA4C-A0D78-AC762-4E4D0-FAD03-C9483"

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/base16-default.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# Window resizing signal
shopt -s checkwinsize
